In [5]:
# Introdución a Numpy 

In [1]:
import numpy as np

# Arrays 
Es una estructura de datos 
un axis "eje"
nu shape (3 filas,5 columnas) "distribución"
un size 15 "tamaño"

In [11]:
# Array cuyos valores son todo 0 
a = np.zeros((3,5)) 
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [12]:
print(a.ndim) 
print (a.shape)
print (a.size) 

2
(3, 5)
15


# describe el Array

In [9]:
#ejemplo 2 
b = np.zeros((2,3,4))
print(b)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [10]:
print(b.ndim) 
print (b.shape)
print (b.size)  

3
(2, 3, 4)
24
